---
title: "NB1_Minimal_model"
---

```{r}
helpers_path = '~/Dropbox/RangelLab/NetworkGLM/helpers/r_helpers/'
source(paste0(helpers_path,'networkModel.R'))
source(paste0(helpers_path,'make_stimtimes.R'))
source(paste0(helpers_path,'generateStructuralNetwork.R'))
source(paste0(helpers_path,'generateSynapticNetwork.R'))
```

```{r}
sim_args = default_args_dict
sim_args$hubnetwork_dsity = .5
sim_args$nodespercommunity = 3
sim_args$showplot = TRUE
sim_args
```

```{r}
S = generateStructuralNetwork(args_dict = sim_args)
S$plt +
  geom_vline(aes(xintercept = 3.5))+
  geom_vline(aes(xintercept = 6.5))+
  geom_hline(aes(yintercept = 3.5))+
  geom_hline(aes(yintercept = 6.5))+
  coord_fixed()+
  scale_fill_gradientn(colors=c("blue", "red"), values = c(0,1))+
  scale_x_continuous(breaks = seq(1, 9, 1))+
  scale_y_continuous(breaks = seq(1, 9, 1))

```

```{r}
W = generateSynapticNetwork(S$W, showplot=FALSE)
```

```{r}
stim_nodes_td = c(1,2,3)
tmp = make_stimtimes(stim_nodes = stim_nodes_td, args_dict = sim_args)
tasktiming = tmp$tasktiming
stimtimes = tmp$stimtimes
rm(tmp)
data.frame(stim = tasktiming) %>%
  mutate(sampling = 1:n()) %>%
  ggplot(aes(x = sampling, y = stim))+
  geom_line()+
  ylab("")+
  scale_y_continuous(breaks=c(0,1))
```

```{r}
sim_args$I = stimtimes
taskdata = networkModel(W$G, args_dict = sim_args)
```

```{r}
data.frame(taskdata) %>%
  mutate(node = row.names(.),
         comm = c(1,1,1,2,2,2,3,3,3)) %>%
  gather(sampling, stim, -node, -comm) %>%
  mutate(sampling = gsub("X", "", sampling),
         sampling = as.numeric(sampling),
         comm = as.factor(comm),
         node = as.factor(node)) %>%
  ggplot(aes(sampling, stim, color=node,))+
  geom_line()+
  facet_wrap(~comm)+
  theme(legend.position = "bottom",
        legend.title = element_blank())+
  guides(color = guide_legend(nrow=3))+
  ylab("")+
  scale_color_manual(values = c("1" = "darkgoldenrod2", "2" = "deepskyblue3", "3" = "darkolivegreen4",
                                "4" = "darkgoldenrod2", "5" = "deepskyblue3", "6" = "darkolivegreen4",
                                "7" = "darkgoldenrod2", "8" = "deepskyblue3", "9" = "darkolivegreen4"))
```